# Site settings
title: My Website
description: Hikmet Efe Canikli's portfolio website
baseurl: "/mywebsite" # the subpath of your site, e.g. /blog
url: "https://hikmetec.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hikmet Efe Canikli
user_description: Cool dude
user_title: Software Developer
email: hikmetefecanikli@gmail.com
twitter_username: -
github_username:  hikmetEC
gplus_username:  -

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
